import { Vocabulary, WordType } from "interfaces";

const mockDataVocab: Vocabulary[] = [
  {
    id: 1,
    word: "apple",
    image: "/image.jpg",
    example: "I eat an apple every day.",
    phonetic: "/ˈæp.əl/",
    meaning: "quả táo",
    wordType: WordType.NOUN,
    topicId: 1,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    word: "run",
    image: "/image.jpg",
    example: "He runs in the park every morning.",
    phonetic: "/rʌn/",
    meaning: "chạy",
    wordType: WordType.VERB,
    topicId: 2,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    word: "happy",
    image: "/image.jpg",
    example: "She feels happy today.",
    phonetic: "/ˈhæp.i/",
    meaning: "hạnh phúc",
    wordType: WordType.ADJECTIVE,
    topicId: 1,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    word: "quickly",
    image: "/image.jpg",
    example: "He finished his homework quickly.",
    phonetic: "/ˈkwɪk.li/",
    meaning: "nhanh chóng",
    wordType: WordType.ADVERB,
    topicId: 4,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    word: "book",
    image: "/image.jpg",
    example: "I read a book every night.",
    phonetic: "/bʊk/",
    meaning: "sách",
    wordType: WordType.NOUN,
    topicId: 1,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    word: "write",
    image: "/image.jpg",
    example: "She writes a letter to her friend.",
    phonetic: "/raɪt/",
    meaning: "viết",
    wordType: WordType.VERB,
    topicId: 2,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    word: "beautiful",
    image: "/image.jpg",
    example: "The sunset is beautiful.",
    phonetic: "/ˈbjuː.tɪ.fəl/",
    meaning: "đẹp",
    wordType: WordType.ADJECTIVE,
    topicId: 3,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    word: "slowly",
    image: "/image.jpg",
    example: "He walks slowly.",
    phonetic: "/ˈsləʊ.li/",
    meaning: "chậm rãi",
    wordType: WordType.ADVERB,
    topicId: 4,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    word: "cat",
    image: "/image.jpg",
    example: "The cat is sleeping on the sofa.",
    phonetic: "/kæt/",
    meaning: "con mèo",
    wordType: WordType.NOUN,
    topicId: 1,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    word: "jump",
    image: "/image.jpg",
    example: "The dog jumps over the fence.",
    phonetic: "/dʒʌmp/",
    meaning: "nhảy",
    wordType: WordType.VERB,
    topicId: 2,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default mockDataVocab;
