import {
  LevelsEnum,
  RolesEnum,
  Route,
  RouteNode,
  RouteNodeEnum,
  User,
} from "interfaces";

const routeNodeData: RouteNode[] = [
  {
    id: 1,
    status: true,
    serial: 1,
    routeId: 1,
    nodeId: 1,
    type: RouteNodeEnum.VOCABULARY,
    title: "Vocabulary 1",
    description: "Description of Lesson 1",
    image: "/image.jpg",
  },
  {
    id: 2,
    status: true,
    serial: 2,
    routeId: 1,
    nodeId: 2,
    type: RouteNodeEnum.GRAMMAR,
    title: "Grammar 1",
    description: "Description of Grammar 1",
    image: "/image.jpg",
  },
  {
    id: 3,
    status: true,
    serial: 3,
    routeId: 1,
    nodeId: 3,
    type: RouteNodeEnum.READING,
    title: "Reading 1",
    description: "Description of Reading 1",
    image: "/image.jpg",
  },
  {
    id: 4,
    status: true,
    serial: 4,
    routeId: 1,
    nodeId: 1,
    type: RouteNodeEnum.MIXING_TEST,
    title: "Mixing Test 1",
    description: "Description of Mixing 1",
    image: "/image.jpg",
  },
  {
    id: 5,
    status: true,
    serial: 5,
    routeId: 1,
    nodeId: 2,
    type: RouteNodeEnum.READING_TEST,
    title: "Reading Test 1",
    description: "Description of Reading 1",
    image: "/image.jpg",
  },
  {
    id: 6,
    status: true,
    serial: 6,
    routeId: 1,
    nodeId: 3,
    type: RouteNodeEnum.LISTENING_TEST,
    title: "Listening Test 1",
    description: "Description of Listening 1",
    image: "/image.jpg",
  },
];

const routeData: Route[] = [
  {
    id: 1,
    status: true,
    title: "Route 1",
    image: "/image.jpg",
    description: "Description of Route 1",
    routeNodes: routeNodeData,
    ownerId: 1,
  },
  {
    id: 2,
    status: true,
    title: "Route 2",
    image: "/image.jpg",
    description: "Description of Route 2",
    routeNodes: routeNodeData,
    ownerId: 1,
  },
];
const mockTeacher: User = {
  id: "1",
  avatar: "/image.jpg",
  email: "teacher@example.com",
  levelEnum: LevelsEnum.BACHELOR,
  name: "John Doe",
  password: "",
  roleEnum: RolesEnum.TEACHER,
  status: true,
  phoneNumber: "123456789",
  dateOfBirth: new Date(),
};
export const mockData = {
  routes: routeData,
  teacher: mockTeacher,
};
