import { LevelsEnum, RolesEnum, User } from "interfaces";

export const mockData: User[] = [
  {
    id: 1,
    avatar: "/image.jpg",
    email: "student1@example.com",
    name: "Student One",
    password: "password123",
    role: RolesEnum.STUDENT,
    phoneNumber: "123-456-7890",
    dateOfBirth: new Date("2005-05-15"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    avatar: "https://example.com/avatar2.jpg",
    email: "teacher1@example.com",
    level: LevelsEnum.PROFESSOR,
    name: "Teacher One",
    password: "password123",
    role: RolesEnum.TEACHER,
    phoneNumber: "987-654-3210",
    dateOfBirth: new Date("1985-08-25"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    avatar: "https://example.com/avatar3.jpg",
    email: "student2@example.com",
    level: LevelsEnum.BACHELOR,
    name: "Student Two",
    password: "password123",
    role: RolesEnum.STUDENT,
    phoneNumber: "123-456-7891",
    dateOfBirth: new Date("2004-04-10"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
