import { LevelsEnum, RolesEnum, User } from "interfaces";

export const mockData: User[] = [
  {
    id: 1,
    avatar: "/image.jpg",
    email: "student1@example.com",
    levelEnum: LevelsEnum.STUDENT,
    name: "Student One",
    password: "password123",
    roleEnum: RolesEnum.STUDENT,
    phoneNumber: "123-456-7890",
    dateOfBirth: new Date("2005-05-15"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    avatar: "https://example.com/avatar2.jpg",
    email: "teacher1@example.com",
    levelEnum: LevelsEnum.PROFESSOR,
    name: "Teacher One",
    password: "password123",
    roleEnum: RolesEnum.TEACHER,
    phoneNumber: "987-654-3210",
    dateOfBirth: new Date("1985-08-25"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    avatar: "https://example.com/avatar3.jpg",
    email: "student2@example.com",
    levelEnum: LevelsEnum.BACHELOR,
    name: "Student Two",
    password: "password123",
    roleEnum: RolesEnum.STUDENT,
    phoneNumber: "123-456-7891",
    dateOfBirth: new Date("2004-04-10"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    avatar: "https://example.com/avatar4.jpg",
    email: "admin@example.com",
    levelEnum: LevelsEnum.PROFESSOR,
    name: "Admin User",
    password: "admin123",
    roleEnum: RolesEnum.ADMIN,
    phoneNumber: "987-654-3211",
    dateOfBirth: new Date("1990-11-20"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    avatar: "https://example.com/avatar5.jpg",
    email: "teacher2@example.com",
    levelEnum: LevelsEnum.MASTER,
    name: "Teacher Two",
    password: "password123",
    roleEnum: RolesEnum.TEACHER,
    phoneNumber: "987-654-3212",
    dateOfBirth: new Date("1982-07-12"),
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
