import {
  Listening,
  Reading,
  Speaking,
  Topic,
  Writing,
  Grammar,
  Vocabulary,
  WordType,
  WritingAnswer,
} from "interfaces";

const topics: Topic[] = [
  {
    id: 1,
    title: "Introduction to Grammar",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Basics of grammar",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Tenses Overview",
    image:
      "https://plus.unsplash.com/premium_photo-1683887033937-edf8d23dd67f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHwwfHx8MA%3D%3D",
    description: "Learn about tenses",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "Parts of Speech",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Detailed explanation of parts of speech",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: "Sentence Structure",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Forming sentences correctly",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    title: "Verb Usage",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "How to use verbs",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    title: "Noun Types",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Types of nouns",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    title: "Adjectives and Adverbs",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Modifiers in sentences",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    title: "Punctuation Rules",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "How to punctuate correctly",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    title: "Common Mistakes",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Avoid common grammar errors",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    title: "Advanced Grammar",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "For advanced learners",
    status: true,
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const grammars: Grammar[] = [
  {
    id: 1,
    title: "Present Simple",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",

    description: "This is description",
    status: true,
    file: "./document.docx",
    questions: [],
    definition: "This is definition",
    example: "This is example",
    tips: ["tip1", "tip2", "tip3"],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: "Past Simple",
    image:
      "https://plus.unsplash.com/premium_photo-1683887033858-be37b32f17a9?q=80&w=1769&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "This is description",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: "Future Simple",
    image: "future_simple.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: "Present Continuous",
    image: "present_continuous.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    title: "Past Continuous",
    image: "past_continuous.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    title: "Future Continuous",
    image: "future_continuous.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    title: "Present Perfect",
    image: "present_perfect.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    title: "Past Perfect",
    image: "past_perfect.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    title: "Future Perfect",
    image: "future_perfect.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    title: "Conditional Sentences",
    image: "conditionals.jpg",
    description: "",
    definition: "",
    example: "",
    tips: ["tip1", "tip2", "tip3"],
    status: true,
    file: "./document.docx",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const readings: Reading[] = [
  {
    id: 1,
    title: "Reading Basics",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Introduction to reading skills",
    status: true,
    file: "reading_basics.pdf",
    questions: [],
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    preparationId: 1,
  },
];

const speakings: Speaking[] = [
  {
    id: 1,
    title: "Introduction Speech",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "How to introduce yourself",
    status: true,
    topic: "Self-Introduction",
    duration: 120,
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    preparationId: 1,
  },
];

const listenings: Listening[] = [
  {
    id: 1,
    title: "Basic Listening",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Improve basic listening",
    status: true,
    audio: "basic_listening.mp3",
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    questions: [1, 2, 3, 4],
    transcript: "",
    preparationId: 1,
  },
];

const writings: Writing[] = [
  {
    id: 1,
    title: "Basic Writing",
    image:
      "https://images.unsplash.com/photo-1700773428278-13f13630d18d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxlc3NvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Learn basic writing skills",
    status: true,
    topic: "Basics",
    views: 0,
    routeNodeId: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    file: "/document.docx",
    paragraph:
      "The quick brown jumps over the lazy dog. This sentence contains all the letters of the English . It is often used for typing practice.",
    questions: [1, 2],
    tips: [
      "Tip 1: Always start with a clear topic sentence.",
      "Tip 2: Use transition words to connect ideas.",
    ],
    preparationId: 1,
  },
];

const listVocabulary: Vocabulary[] = [
  {
    id: 1,
    word: "apple",
    image:
      "https://plus.unsplash.com/premium_photo-1724249989963-9286e126af81?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phonetic: "/ˈæp.l̩/",
    meaning: "Táo",
    status: true,
    wordType: WordType.NOUN,
    example: "An apple a day keeps the doctor away",
    topicId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    word: "run",
    image:
      "https://plus.unsplash.com/premium_photo-1683140692372-26163cb10c8c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phonetic: "/rʌn/",
    meaning: "Chạy",
    status: true,
    wordType: WordType.VERB,
    topicId: 1,
    example: "An apple a day keeps the doctor away",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    word: "beautiful",
    image:
      "https://plus.unsplash.com/premium_photo-1683140692372-26163cb10c8c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phonetic: "/ˈbjuː.tɪ.fəl/",
    meaning: "Đẹp",
    status: true,
    wordType: WordType.ADJECTIVE,
    topicId: 1,
    example: "An apple a day keeps the doctor away",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    word: "quickly",
    image:
      "https://plus.unsplash.com/premium_photo-1683140692372-26163cb10c8c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phonetic: "/ˈkwɪk.li/",
    meaning: "Nhanh",
    status: true,
    wordType: WordType.ADVERB,
    topicId: 1,
    example: "An apple a day keeps the doctor away",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    word: "tree",
    image:
      "https://images.unsplash.com/reserve/bOvf94dPRxWu0u3QsPjF_tree.jpg?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phonetic: "/triː/",
    meaning: "Cây",
    status: true,
    wordType: WordType.NOUN,
    topicId: 1,
    example: "An apple a day keeps the doctor away",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const writingAnswers: WritingAnswer[] = [
  {
    id: 1,
    status: true,
    missingIndex: 3,
    correctAnswer: "fox",
    writingId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    status: true,
    missingIndex: 17,
    correctAnswer: "alphabet",
    writingId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    status: true,
    missingIndex: 10,
    correctAnswer: "nuances",
    writingId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    status: true,
    missingIndex: 25,
    correctAnswer: "emotion",
    writingId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockData = {
  topics,
  grammars,
  readings,
  speakings,
  listenings,
  writings,
  listVocabulary,
  writingAnswers,
};
